export interface Question {
    id: string;
    question: {
        en: string;
        es: string;
        ca: string;
    };
    options: {
        en: string[];
        es: string[];
        ca: string[];
    };
    correctIndex: number;
}

export const mealPlannerQuestions: Question[] = [
    {
        id: 'q1',
        question: {
            en: 'What privacy settings can you configure when creating a new meal plan?',
            es: '¿Qué ajustes de privacidad puedes configurar al crear un nuevo plan de comidas?',
            ca: 'Quins paràmetres de privadesa pots configurar al crear un nou pla de menjars?',
        },
        options: {
            en: [
                'Public or Private',
                'Only visible to administrator accounts',
                'Only visible to users who like your recipes',
                'Visible only after receiving admin approval',
            ],
            es: [
                'Público o Privado',
                'Solo visible para cuentas de administrador',
                'Solo visible para usuarios a los que les gustan tus recetas',
                'Visible solo después de recibir la aprobación del administrador',
            ],
            ca: [
                'Públic o Privat',
                "Només visible per a comptes d'administrador",
                'Només visible per a usuaris a qui els agraden les teves receptes',
                "Visible només després de rebre l'aprovació de l'administrador",
            ],
        },
        correctIndex: 0,
    },
    {
        id: 'q2',
        question: {
            en: 'What are the four meal slots available for each day of the week in the planner?',
            es: '¿Cuáles son los cuatro espacios de comida disponibles para cada día de la semana en el planificador?',
            ca: 'Quins són els quatre espais de menjar disponibles per a cada dia de la setmana al planificador?',
        },
        options: {
            en: [
                'Morning, Afternoon, Evening, Night',
                'Breakfast, Lunch, Dinner, Snack',
                'Appetizer, Main Course, Dessert, Drinks',
                'Fast, Feast, Snack, Supplement',
            ],
            es: [
                'Mañana, Tarde, Tarde-Noche, Noche',
                'Desayuno, Almuerzo, Cena, Snack',
                'Aperitivo, Plato Principal, Postre, Bebidas',
                'Ayuno, Banquete, Snack, Suplemento',
            ],
            ca: [
                'Matí, Tarda, Vespre, Nit',
                'Esmorzar, Dinar, Sopar, Snack',
                'Aperitiu, Plat Principal, Postres, Begudes',
                'Ajuni, Banquet, Snack, Suplement',
            ],
        },
        correctIndex: 1,
    },
    {
        id: 'q3',
        question: {
            en: 'How is the weekly shopping list generated for a meal plan on Jorbites?',
            es: '¿Cómo se genera la lista de compras semanal para un plan de comidas en Jorbites?',
            ca: 'Com es genera la llista de compres setmanal per a un pla de menjars a Jorbites?',
        },
        options: {
            en: [
                'You must type in each ingredient manually',
                'It is generated by scanning a printed receipt',
                'Jorbites automatically compiles all ingredients from all recipes added to your plan',
                'It is generated by picking random kitchen stock recommendations',
            ],
            es: [
                'Debes escribir cada ingrediente manualmente',
                'Se genera escaneando un recibo impreso',
                'Jorbites compila automáticamente todos los ingredientes de todas las recetas agregadas a tu plan',
                'Se genera seleccionando recomendaciones aleatorias de inventario de cocina',
            ],
            ca: [
                "Heu d'escriure cada ingredient manualment",
                'Es genera escanejant un rebut imprès',
                'Jorbites compila automàticament tots els ingredients de totes les receptes afegides al teu pla',
                "Es genera seleccionant recomanacions aleatòries d'inventari de cuina",
            ],
        },
        correctIndex: 2,
    },
    {
        id: 'q4',
        question: {
            en: 'What file format does Jorbites use when you export your meal plan to sync with external calendars?',
            es: '¿Qué formato de archivo utiliza Jorbites cuando exportas tu plan de comidas para sincronizarlo con calendarios externos?',
            ca: 'Quin format de fitxer utilitza Jorbites quan exportes el teu pla de menjars per sincronitzar-lo amb calendaris externs?',
        },
        options: {
            en: [
                '.pdf format',
                '.csv sheet format',
                '.ics calendar format',
                '.json code format',
            ],
            es: [
                'Formato .pdf',
                'Formato de hoja .csv',
                'Formato de calendario .ics',
                'Formato de código .json',
            ],
            ca: [
                'Format .pdf',
                'Format de full .csv',
                'Format de calendari .ics',
                'Format de codi .json',
            ],
        },
        correctIndex: 2,
    },
    {
        id: 'q5',
        question: {
            en: 'Under what conditions can you edit the recipe list or details of a meal plan?',
            es: '¿Bajo qué condiciones puedes editar la lista de recetas o los detalles de un plan de comidas?',
            ca: "Sota quines condicions pots editar la llista de receptes o els detalls d'un pla de menjars?",
        },
        options: {
            en: [
                'Any logged-in community user can edit any plan',
                'Only Jorbites administrator accounts can edit details',
                'Only if you are the owner/creator of the meal plan',
                'Editing is only permitted during the weekend',
            ],
            es: [
                'Cualquier usuario comunitario conectado puede editar cualquier plan',
                'Solo las cuentas de administrador de Jorbites pueden editar los detalles',
                'Solo si eres el propietario/creador del plan de comidas',
                'La edición solo está permitida durante el fin de semana',
            ],
            ca: [
                'Qualsevol usuari comunitari connectat pot editar qualsevol pla',
                "Només els comptes d'administrador de Jorbites poden editar els detalls",
                'Només si ets el propietari/creador del pla de menjars',
                "L'edició només està permesa durant el cap de setmana",
            ],
        },
        correctIndex: 2,
    },
];
