import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
        fontFamily: 'Montserrat',
        padding: 40,
        backgroundColor: '#FFFFFF',
        color: '#1E293B',
    },
    // Cover Styles
    coverContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        borderWidth: 2,
        borderColor: '#C5F0A4',
        margin: 10,
        backgroundColor: '#FCFDFB',
    },
    logo: {
        width: 120,
        height: 120,
        marginBottom: 30,
        objectFit: 'contain',
    },
    coverTitle: {
        fontFamily: 'Playfair Display',
        fontSize: 32,
        fontWeight: 700,
        textAlign: 'center',
        color: '#0F0F0F',
        marginBottom: 10,
    },
    coverSubtitle: {
        fontSize: 12,
        fontWeight: 600,
        color: '#64748B',
        textTransform: 'uppercase',
        letterSpacing: 3,
        marginBottom: 50,
    },
    coverDivider: {
        width: 100,
        height: 3,
        backgroundColor: '#C5F0A4',
        marginBottom: 40,
    },
    coverFooter: {
        position: 'absolute',
        bottom: 40,
        alignItems: 'center',
    },
    coverAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        borderWidth: 1.5,
        borderColor: '#C5F0A4',
        marginBottom: 10,
        objectFit: 'cover',
        alignSelf: 'center',
    },
    coverAuthor: {
        fontSize: 14,
        fontWeight: 700,
        color: '#1E293B',
        marginBottom: 5,
    },
    coverStats: {
        fontSize: 10,
        color: '#64748B',
    },
    // TOC Styles
    tocTitle: {
        fontFamily: 'Playfair Display',
        fontSize: 22,
        fontWeight: 700,
        marginBottom: 30,
        color: '#0F0F0F',
        borderBottomWidth: 2,
        borderBottomColor: '#C5F0A4',
        paddingBottom: 5,
        width: '100%',
    },
    tocItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
        fontSize: 10,
    },
    tocItemText: {
        fontWeight: 600,
        color: '#1E293B',
        maxWidth: '85%',
    },
    tocDots: {
        flexGrow: 1,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        borderStyle: 'dashed',
        marginHorizontal: 8,
    },
    tocPage: {
        fontWeight: 700,
        color: '#64748B',
        width: 25,
        textAlign: 'right',
    },
    // Header/Footer on each page
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 0.5,
        borderBottomColor: '#E2E8F0',
        paddingBottom: 5,
        marginBottom: 20,
        fontSize: 8,
        color: '#94A3B8',
        fontWeight: 600,
    },
    footer: {
        position: 'absolute',
        bottom: 25,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 8,
        color: '#94A3B8',
        fontWeight: 600,
    },
    // Recipe Sheet Styles
    recipeTitle: {
        fontFamily: 'Playfair Display',
        fontSize: 20,
        fontWeight: 700,
        color: '#0F0F0F',
        marginBottom: 4,
    },
    recipeDesc: {
        fontSize: 9,
        color: '#475569',
        marginBottom: 15,
        lineHeight: 1.4,
    },
    metaRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 20,
    },
    metaBadge: {
        backgroundColor: '#F8FAFC',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        fontSize: 8,
        color: '#475569',
        fontWeight: 600,
        borderWidth: 0.5,
        borderColor: '#E2E8F0',
    },
    categoryBadge: {
        backgroundColor: '#EBFCE2',
        borderColor: '#C5F0A4',
        color: '#336611',
    },
    columns: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flex: 1,
    },
    leftCol: {
        width: '42%',
        paddingRight: 10,
    },
    rightCol: {
        width: '54%',
    },
    sectionTitle: {
        fontFamily: 'Playfair Display',
        fontSize: 11,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: 1,
        color: '#0F0F0F',
        borderBottomWidth: 1.5,
        borderBottomColor: '#C5F0A4',
        paddingBottom: 3,
        marginBottom: 10,
    },
    ingredientItem: {
        flexDirection: 'row',
        marginBottom: 6,
        fontSize: 9,
        lineHeight: 1.4,
    },
    bulletPoint: {
        width: 10,
        color: '#84CC16',
        fontWeight: 700,
    },
    ingredientText: {
        flex: 1,
        color: '#334155',
    },
    recipeImageLeft: {
        width: '100%',
        borderRadius: 8,
        marginBottom: 15,
        objectFit: 'cover',
    },
    recipeImageRight: {
        width: '100%',
        height: 220,
        borderRadius: 8,
        marginBottom: 15,
        objectFit: 'cover',
    },
    galleryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    galleryImage: {
        width: '48%',
        height: 80,
        borderRadius: 6,
        objectFit: 'cover',
    },
    stepItem: {
        flexDirection: 'row',
        marginBottom: 8,
        fontSize: 9,
        lineHeight: 1.4,
    },
    stepNum: {
        width: 16,
        fontWeight: 800,
        color: '#65A30D',
    },
    stepText: {
        flex: 1,
        color: '#334155',
    },
});
