import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import useSWR, { mutate } from 'swr';
import { useTranslation } from 'react-i18next';
import axios from 'axios';
import { toast } from 'react-hot-toast';
import useDraftInviteModal from '@/app/hooks/useDraftInviteModal';
import { axiosFetcher } from '@/app/utils/fetcher';
import { SafeUser } from '@/app/types';
import { SharedDraft, CoCookRole } from '@/app/types/draft';
import { MAX_CO_COOKS } from '@/app/utils/constants';

export function useDraftInvite(currentUser?: SafeUser | null) {
    const { t } = useTranslation();
    const { isOpen, draftId, onClose } = useDraftInviteModal();

    const [isRegenerating, setIsRegenerating] = useState(false);
    const [mutatingUserId, setMutatingUserId] = useState<string | null>(null);
    const [isAddingUser, setIsAddingUser] = useState(false);
    const [regeneratedToken, setRegeneratedToken] = useState<string | null>(
        null
    );

    useEffect(() => {
        setRegeneratedToken(null);
    }, [draftId, isOpen]);

    const {
        data: draft,
        isLoading: isDraftLoading,
        mutate: mutateDraft,
    } = useSWR<SharedDraft>(
        isOpen && draftId
            ? `/api/draft?draftId=${encodeURIComponent(draftId)}`
            : null,
        axiosFetcher,
        {
            revalidateOnFocus: true,
            revalidateOnMount: true,
        }
    );

    const allUserIds = useMemo(() => {
        if (!draft) return [];
        const idSet = new Set<string>();
        if (draft.ownerId) idSet.add(draft.ownerId);
        if (Array.isArray(draft.coCooksIds)) {
            draft.coCooksIds.forEach((id) => {
                if (id) idSet.add(id);
            });
        }
        return Array.from(idSet);
    }, [draft]);

    const { data: usersList } = useSWR<SafeUser[]>(
        isOpen && allUserIds.length > 0
            ? `/api/users/multiple?ids=${allUserIds.join(',')}`
            : null,
        axiosFetcher
    );

    const usersMap = useMemo(() => {
        const map = new Map<string, SafeUser>();
        if (Array.isArray(usersList)) {
            usersList.forEach((u) => {
                if (u?.id) map.set(u.id, u);
            });
        }
        return map;
    }, [usersList]);

    const isOwner = Boolean(
        currentUser?.id && draft?.ownerId && currentUser.id === draft.ownerId
    );

    const effectiveToken = regeneratedToken || draft?.inviteToken;

    const inviteUrl = useMemo(() => {
        if (!effectiveToken || !draftId) return '';
        const origin =
            typeof window !== 'undefined' ? window.location.origin : '';
        return `${origin}/recipes/new?draft=${draftId}&token=${effectiveToken}`;
    }, [effectiveToken, draftId]);

    const handleGenerateOrRegenerate = useCallback(
        async (isAutoInitial: boolean = false) => {
            if (!draftId) return;
            setIsRegenerating(true);
            try {
                const res = await axios.post('/api/draft/invite', {
                    draftId,
                    regenerate: Boolean(effectiveToken),
                });
                if (res.data?.inviteToken) {
                    setRegeneratedToken(res.data.inviteToken);
                }
                if (res.data?.draft) {
                    await mutateDraft(res.data.draft, false);
                } else {
                    await mutateDraft();
                }
                mutate('/api/draft/active');
                mutate(`/api/draft?draftId=${encodeURIComponent(draftId)}`);
                if (!isAutoInitial && effectiveToken) {
                    toast.success(
                        t('invite_link_regenerated', {
                            defaultValue: 'Invite link regenerated!',
                        })
                    );
                }
            } catch {
                if (!isAutoInitial) {
                    toast.error(
                        t('something_went_wrong', {
                            defaultValue: 'Something went wrong',
                        })
                    );
                }
            } finally {
                setIsRegenerating(false);
            }
        },
        [draftId, effectiveToken, mutateDraft, t]
    );

    const hasAutoGeneratedRef = useRef(false);

    useEffect(() => {
        if (!isOpen) {
            hasAutoGeneratedRef.current = false;
        }
    }, [isOpen]);

    useEffect(() => {
        hasAutoGeneratedRef.current = false;
    }, [draftId]);

    useEffect(() => {
        if (
            isOpen &&
            draftId &&
            isOwner &&
            draft &&
            !effectiveToken &&
            !isRegenerating &&
            !hasAutoGeneratedRef.current
        ) {
            hasAutoGeneratedRef.current = true;
            handleGenerateOrRegenerate(true);
        }
    }, [
        isOpen,
        draftId,
        isOwner,
        draft,
        effectiveToken,
        isRegenerating,
        handleGenerateOrRegenerate,
    ]);

    const handleRoleChange = useCallback(
        async (targetUserId: string, newRole: CoCookRole) => {
            if (!draftId) return;
            setMutatingUserId(targetUserId);
            await mutateDraft(
                (prev) =>
                    prev
                        ? {
                              ...prev,
                              coCookRoles: {
                                  ...prev.coCookRoles,
                                  [targetUserId]: newRole,
                              },
                          }
                        : prev,
                false
            );
            try {
                const res = await axios.patch('/api/draft/role', {
                    draftId,
                    targetUserId,
                    role: newRole,
                });
                if (res.data?.draft) {
                    await mutateDraft(res.data.draft, false);
                } else {
                    await mutateDraft();
                }
                mutate('/api/draft/active');
                mutate(`/api/draft?draftId=${encodeURIComponent(draftId)}`);
                toast.success(
                    t('role_updated', { defaultValue: 'Role updated' })
                );
            } catch {
                await mutateDraft();
                toast.error(
                    t('something_went_wrong', {
                        defaultValue: 'Failed to update role',
                    })
                );
            } finally {
                setMutatingUserId(null);
            }
        },
        [draftId, mutateDraft, t]
    );

    const handleRemoveCollaborator = useCallback(
        async (targetUserId: string) => {
            if (!draftId) return;
            const isSelf = targetUserId === currentUser?.id;
            setMutatingUserId(targetUserId);
            try {
                await axios.delete(
                    `/api/draft/collaborator?draftId=${encodeURIComponent(draftId)}&userId=${encodeURIComponent(targetUserId)}`
                );
                if (isSelf) {
                    toast.success(
                        t('left_draft', {
                            defaultValue: 'You have left the draft',
                        })
                    );
                    onClose();
                } else {
                    toast.success(
                        t('co_cook_removed', {
                            defaultValue: 'Co-cook removed',
                        })
                    );
                    await mutateDraft();
                }
                mutate('/api/draft/active');
                mutate(`/api/draft?draftId=${encodeURIComponent(draftId)}`);
            } catch {
                toast.error(
                    t('something_went_wrong', {
                        defaultValue: 'Failed to remove collaborator',
                    })
                );
            } finally {
                setMutatingUserId(null);
            }
        },
        [currentUser?.id, draftId, mutateDraft, onClose, t]
    );

    const handleAddCollaborator = useCallback(
        async (user: SafeUser) => {
            if (!draftId || isAddingUser) return;
            if ((draft?.coCooksIds?.length || 0) >= MAX_CO_COOKS) {
                toast.error(
                    t('max_cooks_reached', {
                        defaultValue: `Maximum of ${MAX_CO_COOKS} co-cooks allowed`,
                    })
                );
                return;
            }
            setIsAddingUser(true);
            try {
                const res = await axios.post('/api/draft/collaborator', {
                    draftId,
                    userId: user.id,
                    role: 'editor',
                });
                if (res.data?.draft) {
                    await mutateDraft(res.data.draft, false);
                } else {
                    await mutateDraft();
                }
                mutate('/api/draft/active');
                mutate(`/api/draft?draftId=${encodeURIComponent(draftId)}`);
                toast.success(
                    t('co_cook_added', { defaultValue: 'Co-cook added' })
                );
            } catch (err: any) {
                const msg =
                    err?.response?.data?.message ||
                    err?.response?.data?.error ||
                    t('something_went_wrong', {
                        defaultValue: 'Failed to add co-cook',
                    });
                toast.error(msg);
            } finally {
                setIsAddingUser(false);
            }
        },
        [draft?.coCooksIds?.length, draftId, isAddingUser, mutateDraft, t]
    );

    return {
        isOpen,
        draftId,
        onClose,
        draft,
        isDraftLoading,
        usersMap,
        isOwner,
        inviteUrl,
        isRegenerating,
        handleRegenerate: () => handleGenerateOrRegenerate(false),
        mutatingUserId,
        handleRoleChange,
        handleRemoveCollaborator,
        isAddingUser,
        handleAddCollaborator,
        t,
    };
}
