name: Format Code on Jules Push

on:
  push: # Triggers on push to any branch

jobs:
  format_code:
    if: github.actor == 'google-labs-jules[bot]' # Condition for the actor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run formatting script
        run: npm run format

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet || (git commit -am "Automated formatting by npm script" && git push)
