name: Lighthouse Audit
on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Start server
        run: npm run start &
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v1
        with:
          urls: http://localhost:3000
          uploadArtifacts: true
