name: Oxlint

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  oxlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 11
      - run: pnpm dlx oxlint@latest --deny-warnings
